format = """
$nix_shell\
$directory\
[ ](fg:#394260 bg:#1d2230)\
$time\
[ ](fg:#1d2230)\
\n$character
"""

[nix_shell]
style = "fg:#769ff0 bg:#394260"
format = '[$symbol]($style)'
symbol = '❄️'

[directory]
style = "fg:#769ff0 bg:#394260"
format = "[ $path]($style)"
truncation_length = 20
truncation_symbol = "…/"
truncate_to_repo = false

[directory.substitutions]
"documents" = "󰈙 "
"downloads" = " "
"music" = " "
"images" = " "

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'
